### ISSUE TITLE
Can't start

### ISSUE THREAD

**Issue by E3D3** [kikito/lua_missions#18]
I got the following error:

[missions]$ lua missions.lua 
lua: ./lib/agent.lua:127: attempt to call global 'setfenv' (a nil value)
stack traceback:
        ./lib/agent.lua:127: in function 'load_mission'
        ./lib/agent.lua:212: in function 'run_missions'
        missions.lua:29: in main chunk
        [C]: in ?

My Lua-version is:
Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio

**Comment by kikito** [comment]
Hi @E3D3 

The version of Lua you where using (Lua 5.2) was not supported. I say *was* because I just made a change which should make it work.

Please pull the changes from the repo with `git pull`, or re-download it, and it should work.

I will close this issue now - if your problem persist, please reopen.

Regards!

**Comment by E3D3** [comment]
It works, thanks.
